version: '3'

services:
  db:
    image: mariadb:10
    command: mysqld --sql_mode="" --character-set-server=latin1 --collation-server=latin1_german2_ci
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8081:80
  web:
    build: .
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./www:/var/www/html
